language: node_js
node_js :
 - "0.12"
before_script:
 - npm install -g bower
 - bower install
 - npm install -g --verbose qunit-phantomjs-runner@2.1.0
script: phantomjs test/run-qunit.js test/test.html

